services:
  - type: web
    name: makita
    env: python
    region: ohio
    plan: free
    buildCommand: |
      pip install -r makita/requirements.txt &&
      playwright install chromium
    startCommand: python makita/main.py
    healthCheckPath: /saude
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: FB_C_USER
        sync: false
      - key: FB_XS
        sync: false
      - key: FB_FR
        sync: false
      - key: TW_AUTH_TOKEN
        sync: false
      - key: TW_CT0
        sync: false
      - key: TWITTER_COOKIES_B64
        sync: false
      - key: REDDIT_COOKIES_B64
        sync: false
      - key: INVITE_CODES
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BROWSERLESS_TOKEN
        sync: false
      - key: DEBUG
        sync: false
